### ISSUE TITLE
Define ZFC as a first-order theory

### ISSUE THREAD

**Issue by flypitch** [flypitch/flypitch#5]
We should decide whether or start with just a single binary relation, or work with a conservative extension with symbols added for emptyset, pairing, etc. The latter might be useful by itself.

We should work towards the goals of:

1. stating the continuum hypothesis

2. showing Mario's "model" of ZFC is a model of ZFC.

**Comment by fpvandoorn** [comment]
I think we want ZFC to be a theory in the language with a single binary relation `∈`. However, when writing sentences in ZFC (like CH, and also the more complicated axioms (infinity, choice)), we want to write them in a different language `L'`, and then write a method of transforming them into the language `{∈}`. Also, if `ZFC'` are the axioms in `L'`, then we need to show that if `ZFC'  ⊢ A` then `ZFC ⊢ translation(A)`.

I think we want ZFC to be in the language `{∈}`, because that will proving meta-theoretic properties probably easiest.
